# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO.xci
# IP: The module: 'config_data_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO/config_data_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_data_FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO/config_data_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO.xci
# IP: The module: 'config_data_FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO/config_data_FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO/config_data_FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.srcs/sources_1/ip/config_data_FIFO/config_data_FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'config_data_FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
