# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 6
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a [current_project]
add_files -quiet C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.runs/config_data_FIFO_synth_1/config_data_FIFO.dcp
set_property used_in_implementation false [get_files C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/project_1/project_1.runs/config_data_FIFO_synth_1/config_data_FIFO.dcp]
read_vhdl -library axi_FPGA_configuration_controller {
  C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/VHDL_Sources/Synthesis_Sources/clock_divider.vhd
  C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/VHDL_Sources/Synthesis_Sources/FPGA_configuration_controller_pkg.vhd
  C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/VHDL_Sources/Synthesis_Sources/FPGA_configuration_controller.vhd
  C:/custom_xilinx_ip/MyProcessorIPLib/pcores/axi_FPGA_configuration_controller_v1_00_a/VHDL_Sources/Synthesis_Sources/axi_FPGA_configuration_controller.vhd
}
synth_design -top axi_FPGA_configuration_controller -part xc7z010clg400-1
write_checkpoint -noxdef axi_FPGA_configuration_controller.dcp
catch { report_utilization -file axi_FPGA_configuration_controller_utilization_synth.rpt -pb axi_FPGA_configuration_controller_utilization_synth.pb }
